# Generated by Django 5.2.1 on 2025-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('StudentId', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=15)),
                ('Date_of_Birth', models.DateField()),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('Created_at', models.DateTimeField()),
            ],
        ),
    ]
